batch_size: 8
ckp: ''
ckp_freq: 1
classes:
- benign
- other
- ransomware
cuda: true
epochs: 2
exp_name: exp
image_dir: /home/thinhnn/Downloads/malware/RGB
image_size: 224,224
is_loaded: true
k_fold: 5
lr: 0.0001
model: IMCEC
num_class: 3
num_workers: 8
result_dir: result
save_dir: ''
train_log_step: 100
